version: "3.8"
services:
    nodeserver1:
        build:
            context: ./app1
        ports:
            - "6000:6000"
    nodeserver2:
        build:
            context: ./app2
        ports:
            - "6001:6001"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"